// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxGnNtG2ZkZ3dPqXFO6Nv_buJdJ5VDKQ',
    appId: '1:678141302743:web:879371e9ebc311b77c1d92',
    messagingSenderId: '678141302743',
    projectId: 'getx-52c37',
    authDomain: 'getx-52c37.firebaseapp.com',
    storageBucket: 'getx-52c37.firebasestorage.app',
    measurementId: 'G-5MVSPK58RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcKQJgC9nwpodYWFq09HIlODfVKm_Zy2U',
    appId: '1:678141302743:android:c6beb784c67232ad7c1d92',
    messagingSenderId: '678141302743',
    projectId: 'getx-52c37',
    storageBucket: 'getx-52c37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChI0yMQNm4A6sWInQ5HDuqr1mmVkbEHB0',
    appId: '1:678141302743:ios:41355a85721cb2d97c1d92',
    messagingSenderId: '678141302743',
    projectId: 'getx-52c37',
    storageBucket: 'getx-52c37.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChI0yMQNm4A6sWInQ5HDuqr1mmVkbEHB0',
    appId: '1:678141302743:ios:41355a85721cb2d97c1d92',
    messagingSenderId: '678141302743',
    projectId: 'getx-52c37',
    storageBucket: 'getx-52c37.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxGnNtG2ZkZ3dPqXFO6Nv_buJdJ5VDKQ',
    appId: '1:678141302743:web:6bee12ecd87a2ab17c1d92',
    messagingSenderId: '678141302743',
    projectId: 'getx-52c37',
    authDomain: 'getx-52c37.firebaseapp.com',
    storageBucket: 'getx-52c37.firebasestorage.app',
    measurementId: 'G-DRHW8SH7QN',
  );
}
